import React from 'react'

const Footer = () => {
  return (
    <div>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste ipsam omnis quas pariatur! Voluptatum dignissimos minima ipsam et, neque ullam explicabo amet soluta ipsum dolorum quod aliquid vero magni in veniam quis nemo, natus sit sed culpa dolore? Dolor, porro nesciunt fugiat odio illum voluptate dignissimos nihil adipisci libero quis, quibusdam officiis! Soluta vero numquam dolorem at, voluptas sapiente veniam repudiandae neque excepturi et blanditiis ea nobis optio commodi iusto nisi, delectus cum eius amet ad! Nostrum veritatis expedita adipisci accusamus dolore error vitae, tempora at quae quia omnis earum natus quod ratione modi minus eum iusto! Sint error itaque molestias eaque inventore necessitatibus eius similique odit temporibus minima possimus ad, repudiandae, cumque quas laudantium eum cum rerum aliquam optio alias ratione, magni id pariatur. Nesciunt, dolor saepe repellat voluptate magni similique aut et vero fugit molestias id fugiat nemo enim deleniti quibusdam deserunt hic reprehenderit provident, labore incidunt laboriosam eveniet excepturi. Enim iure distinctio tempora optio, dicta quia libero laudantium iusto quisquam tempore qui aspernatur accusantium eius vero molestias quos, consectetur voluptatum ad placeat quod. Mollitia nemo, voluptatibus doloremque, dignissimos est vel sint impedit nobis inventore deserunt iure ducimus quos cumque alias dolorum voluptas officia facere, blanditiis repudiandae quidem.
      </p>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste ipsam omnis quas pariatur! Voluptatum dignissimos minima ipsam et, neque ullam explicabo amet soluta ipsum dolorum quod aliquid vero magni in veniam quis nemo, natus sit sed culpa dolore? Dolor, porro nesciunt fugiat odio illum voluptate dignissimos nihil adipisci libero quis, quibusdam officiis! Soluta vero numquam dolorem at, voluptas sapiente veniam repudiandae neque excepturi et blanditiis ea nobis optio commodi iusto nisi, delectus cum eius amet ad! Nostrum veritatis expedita adipisci accusamus dolore error vitae, tempora at quae quia omnis earum natus quod ratione modi minus eum iusto! Sint error itaque molestias eaque inventore necessitatibus eius similique odit temporibus minima possimus ad, repudiandae, cumque quas laudantium eum cum rerum aliquam optio alias ratione, magni id pariatur. Nesciunt, dolor saepe repellat voluptate magni similique aut et vero fugit molestias id fugiat nemo enim deleniti quibusdam deserunt hic reprehenderit provident, labore incidunt laboriosam eveniet excepturi. Enim iure distinctio tempora optio, dicta quia libero laudantium iusto quisquam tempore qui aspernatur accusantium eius vero molestias quos, consectetur voluptatum ad placeat quod. Mollitia nemo, voluptatibus doloremque, dignissimos est vel sint impedit nobis inventore deserunt iure ducimus quos cumque alias dolorum voluptas officia facere, blanditiis repudiandae quidem.
      </p>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste ipsam omnis quas pariatur! Voluptatum dignissimos minima ipsam et, neque ullam explicabo amet soluta ipsum dolorum quod aliquid vero magni in veniam quis nemo, natus sit sed culpa dolore? Dolor, porro nesciunt fugiat odio illum voluptate dignissimos nihil adipisci libero quis, quibusdam officiis! Soluta vero numquam dolorem at, voluptas sapiente veniam repudiandae neque excepturi et blanditiis ea nobis optio commodi iusto nisi, delectus cum eius amet ad! Nostrum veritatis expedita adipisci accusamus dolore error vitae, tempora at quae quia omnis earum natus quod ratione modi minus eum iusto! Sint error itaque molestias eaque inventore necessitatibus eius similique odit temporibus minima possimus ad, repudiandae, cumque quas laudantium eum cum rerum aliquam optio alias ratione, magni id pariatur. Nesciunt, dolor saepe repellat voluptate magni similique aut et vero fugit molestias id fugiat nemo enim deleniti quibusdam deserunt hic reprehenderit provident, labore incidunt laboriosam eveniet excepturi. Enim iure distinctio tempora optio, dicta quia libero laudantium iusto quisquam tempore qui aspernatur accusantium eius vero molestias quos, consectetur voluptatum ad placeat quod. Mollitia nemo, voluptatibus doloremque, dignissimos est vel sint impedit nobis inventore deserunt iure ducimus quos cumque alias dolorum voluptas officia facere, blanditiis repudiandae quidem.
      </p>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste ipsam omnis quas pariatur! Voluptatum dignissimos minima ipsam et, neque ullam explicabo amet soluta ipsum dolorum quod aliquid vero magni in veniam quis nemo, natus sit sed culpa dolore? Dolor, porro nesciunt fugiat odio illum voluptate dignissimos nihil adipisci libero quis, quibusdam officiis! Soluta vero numquam dolorem at, voluptas sapiente veniam repudiandae neque excepturi et blanditiis ea nobis optio commodi iusto nisi, delectus cum eius amet ad! Nostrum veritatis expedita adipisci accusamus dolore error vitae, tempora at quae quia omnis earum natus quod ratione modi minus eum iusto! Sint error itaque molestias eaque inventore necessitatibus eius similique odit temporibus minima possimus ad, repudiandae, cumque quas laudantium eum cum rerum aliquam optio alias ratione, magni id pariatur. Nesciunt, dolor saepe repellat voluptate magni similique aut et vero fugit molestias id fugiat nemo enim deleniti quibusdam deserunt hic reprehenderit provident, labore incidunt laboriosam eveniet excepturi. Enim iure distinctio tempora optio, dicta quia libero laudantium iusto quisquam tempore qui aspernatur accusantium eius vero molestias quos, consectetur voluptatum ad placeat quod. Mollitia nemo, voluptatibus doloremque, dignissimos est vel sint impedit nobis inventore deserunt iure ducimus quos cumque alias dolorum voluptas officia facere, blanditiis repudiandae quidem.
      </p>
    </div>
  )
}

export default Footer
